# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  project: '**/FakeOrm.AzureTables/FakeOrm.AzureTables.csproj'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore Package'
  inputs:
    command: 'restore'
    projects: '$(project)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build Package'
  inputs:
    command: 'build'
    projects: '$(project)'


