name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1
      
    - name: Restore dependencies
      run: dotnet restore FakeOrm/FakeOrm.csproj
    - name: Build
      run: dotnet build FakeOrm/FakeOrm.csproj --no-restore 
    - name: Pack
      run: dotnet pack FakeOrm/FakeOrm.csproj --verbosity normal --no-restore --configuration Release --version-suffix ${GITHUB_RUN_NUMBER}
    
